---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: linux_tweet_app
      PROJECT_ID: andiamo-1d849
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACOUNT_KEY }}'

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-docker.pkg.dev/andiamo-1d849/eu.gcr.io --quiet
        
    - name: Build Docker Image , when we have pull event only this will work
      run: docker build -t $IMAGE_NAME:latest .

    - name: For every Commit, Tagging the image with the git commit hash and Push Docker Image to Container Registry (GCR)
      env: 
        COMMIT_TAG: ${{github.sha}}
        
      run: |-
        if [ ${{ github.ref }} == 'refs/heads/main'  && ${{github.event}}== 'push' ]; then
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$COMMIT_TAG
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$COMMIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    
    - name: For every git Tag, Build, Tag and publish Docker Image and push to Container Registry (GCR)
      if: github.ref == 'refs/tags/*' && (github.event_name == 'create' || github.event_name == 'delete')
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
