---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GOOGLE_REGISTRY: gcr.io
  PROJECT_ID: my-project-id
  IMAGE_NAME: linux_tweet_app
  GITHUB_REF: ${{github.ref}}
  GOOGLE_CREDENTIALS: ${{ secrets.SERVICE_ACOUNT_KEY }}
  GOOGLE_PROJECT_ID: my-project-id


jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2


  - name: Authenticate with JSON credentials
    uses: google-github-actions/auth@v1
    with:
      credentials_json: ${{ andiamo-1d849-bac131c64623 }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .