--- 
name: Build and push Image to Google Cloud 
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  tag:
    branches:
    - master
env: 
  IMAGE_NAME: tweet_app
  PROJECT_ID: andiamo-1d849

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ on_push() }}
        tags: ${{ env.GOOGLE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_REF }}
Note: Replace my-project-id with the actual project ID of your Google Cloud project.
You also need to authenticate to Google Cloud by adding a secret to your GitHub repository with the credentials for the service account that has access to Google Artifact Registry. You can follow these instructions for setting up the secret.




armando kotsiai
can you seperate the steps and make the seperate for push pull and tag
Sure, here's an updated example of the CI pipeline that includes separate steps for push, pull request, and tag events and publishing the Docker image to Google Artifact Registry:

yaml
Copy code
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  tag:
    branches:
      - main

env:
  GOOGLE_REGISTRY: gcr.io
  PROJECT_ID: my-project-id
  IMAGE_NAME: linux_tweet_app

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      if: ${{ on_push() }}
      with:
        context: .
        push: true
        tags: ${{ env.GOOGLE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_REF }}

    - name: Build Docker Image (without publishing)
      uses: docker/build-push-action@v2
      if: ${{ !on_push() }}
      with:
        context: .
        push: false

    - name: Tag Docker Image
      uses: docker/build-push-action@v2
      if: ${{ is_tag() }}
      with:
        context: .
        push: true
        tags: ${{ env.GOOGLE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_TAG }}