---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GOOGLE_REGISTRY: gcr.io
  PROJECT_ID: my-project-id
  IMAGE_NAME: linux_tweet_app
  GITHUB_REF: ${{github.ref}}


jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .