---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # tag:
  #   branches:
  #     - main

env:
  GOOGLE_REGISTRY: gcr.io
  PROJECT_ID: my-project-id
  IMAGE_NAME: linux_tweet_app

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      if: ${{ on_push() }}
      with:
        context: .
        push: true
        tags: ${{ env.GOOGLE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_REF }}

    - name: Build Docker Image (without publishing)
      uses: docker/build-push-action@v2
      if: ${{ !on_push() }}
      with:
        context: .
        push: false

    # - name: Tag Docker Image
    #   uses: docker/build-push-action@v2
    #   if: ${{ is_tag() }}
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ env.GOOGLE_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_TAG }}