---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: linux_tweet_app
      PROJECT_ID: andiamo-1d849
      COMMIT_TAG: ${{github.sha}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACOUNT_KEY }}'

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-docker.pkg.dev/andiamo-1d849/eu.gcr.io --quiet


    - name: using
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}

      run: |- 
        if [ "$GITHUB_REF" == "refs/heads/master" ] && [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
          docker build -t $IMAGE_NAME:latest .
        elif [ "$GITHUB_REF" == "refs/heads/master" ] && [ "$GITHUB_EVENT_NAME" == "push" ]; then
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$COMMIT_TAG
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$COMMIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        elif [ "$GITHUB_REF" == "refs/tags/"* ] && [ "$GITHUB_EVENT_NAME" == "create" ] || [ "$GITHUB_EVENT_NAME" == "delete" ]; then
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$(echo $GITHUB_REF | awk -F/ '{print $3}')
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$(echo $GITHUB_REF | awk -F/ '{print $3}')
        fi
      shell: bash

        
   