---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GOOGLE_REGISTRY: gcr.io
  PROJECT_ID: my-project-id
  IMAGE_NAME: linux_tweet_app
  GITHUB_REF: ${{github.ref}}
  GOOGLE_CREDENTIALS: ${{ secrets.SERVICE_ACOUNT_KEY }}


jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Configure Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        credentials: ${{ env.GOOGLE_CREDENTIALS }}


    # - uses: google-github-actions/auth@v0
    #   with: 
    #     credentials: ${{ env.GOOGLE_CREDENTIALS }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .