---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GOOGLE_REGISTRY: gcr.io
  PROJECT_ID: my-project-id
  IMAGE_NAME: linux_tweet_app
  GITHUB_REF: ${{github.ref}}


jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .