name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  create:
    type: tag
    branches:
      - master

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: linux_tweet_app
      PROJECT_ID: andiamo-1d849
      GIT_TAG: ''
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Authenticate with Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACOUNT_KEY }}'
    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v major
    - name: Set the Image Tag
      id: set-image-tag
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        SHA: ${{ steps.increment-git-tag.outputs.sha }}
      run: |
        echo "::set-env name=IMAGE_TAG::${{ if eq(github.event_name, 'push') && eq(github.ref, 'refs/heads/master') }}${{ substr(sha,0,7) }}{{ else if eq(github.event_name, 'pull_request') }}pull_request{{ else }}$GIT_TAG{{ end }}"
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-docker.pkg.dev/andiamo-1d849/eu.gcr.io --quiet
    - name: Push Docker Image to Container Registry (GCR)
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      if: env.IMAGE_TAG != 'pull_request'
      run: |-
        docker tag $IMAGE_NAME:$IMAGE_TAG gcr.io/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG

# ---

# name: CI

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   build-push-gcr:
#     name: Build and Push to GCP
#     runs-on: ubuntu-latest
#     env:
#       IMAGE_NAME: linux_tweet_app
#       PROJECT_ID: andiamo-1d849
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Authenticate with Google Cloud
#       id: 'auth'
#       uses: 'google-github-actions/auth@v0'
#       with:
#         credentials_json: '${{ secrets.SERVICE_ACOUNT_KEY }}'


#     - name: Build Docker Image
#       run: docker build -t $IMAGE_NAME:latest .
    
#     - name: Automatic Tagging of Releases
#       id: increment-git-tag
#       run: |
#         bash ./scripts/git_update.sh -v major
#     - name: Configure Docker Client
#       run: |-
#         gcloud auth configure-docker --quiet
#         gcloud auth configure-docker europe-docker.pkg.dev/andiamo-1d849/eu.gcr.io --quiet
    

#     - name: Push Docker Image to Container Registry (GCR)
#       env:
#        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
#       run: |-
#         docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
#         docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
#         docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
#         docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
